# Setup
title:               Peiru Liu's personal page
tagline:             'Computer Science student at RPI'
description:         'my personal page'
url:                 https://wodecinghaolen.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Peiru Liu
  url:               'https://wodecinghaolen.github.io/'
  email:             peiruliu0104@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y
